spring:
  application:
    name: legacy
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/db?autoreconnect=true&useSSL=false
    username: "user"
    password: "password"
  flyway:
    locations: classpath:db/migration/{vendor}
    url: jdbc:mysql://db:3306/db?autoreconnect=true&useSSL=false
    user: "user"
    password: "password"
server:
  port: 8080